export default Object.freeze({
  ACCOUNT: "Account",
  ACCOUNT_DETAILS: "AccountDetails",
  ADMIN_LISTING_ADD: "AdminAdder",
  ADMIN_LISTING_EDIT: "AdminEdit",
  ADMIN_LISTING_UPDATE: "AdminUpdate",
  MENU: "Menu",
  LISTING_EDIT: "ListingEdit",
  LOGIN: "Login",
  MESSAGES: "Messages",
  REGISTER: "Register",
  WELCOME: "Welcome",
  APP_NAV: "App_Nav",
  ONLINE_ACCOUNT: "Online_Account",
  ORDERS: "Orders",
  ORDERS_SUMMARY: "Summary",
  ONLINE_CHECKBOOK: "Order History",
  USER_ADMIN_HISTORY: "User_Amdin_History",
  USER_ADMIN_HISTORY_DETAILS: "User_Admin_History_Details",
});
